"""Initial enterprise schema

Revision ID: 1d29ffd7b801
Revises: 
Create Date: 2026-05-26 20:05:47.454071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d29ffd7b801'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_parameters',
    sa.Column('parameter_key', sa.String(length=100), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('collection_method', sa.String(length=50), nullable=False),
    sa.Column('collector_module', sa.String(length=100), nullable=True),
    sa.Column('graph_endpoint', sa.String(length=500), nullable=True),
    sa.Column('copilot_relevance', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('excel_row_reference', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_parameters_category'), 'assessment_parameters', ['category'], unique=False)
    op.create_index(op.f('ix_assessment_parameters_id'), 'assessment_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_parameters_parameter_key'), 'assessment_parameters', ['parameter_key'], unique=True)
    op.create_table('connected_tenants',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('app_registration_id', sa.String(length=64), nullable=True),
    sa.Column('encrypted_client_secret', sa.String(length=255), nullable=True),
    sa.Column('consent_status', sa.String(length=50), nullable=False),
    sa.Column('consent_granted_by', sa.String(length=255), nullable=True),
    sa.Column('consent_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_permissions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_assessment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_tenants_id'), 'connected_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_connected_tenants_tenant_id'), 'connected_tenants', ['tenant_id'], unique=True)
    op.create_table('users',
    sa.Column('microsoft_oid', sa.String(length=64), nullable=False),
    sa.Column('microsoft_tid', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microsoft_oid', 'microsoft_tid', name='uq_user_oid_tid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_microsoft_oid'), 'users', ['microsoft_oid'], unique=False)
    op.create_index(op.f('ix_users_microsoft_tid'), 'users', ['microsoft_tid'], unique=False)
    op.create_table('assessment_rules',
    sa.Column('parameter_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('pass_threshold', sa.String(length=255), nullable=True),
    sa.Column('warning_threshold', sa.String(length=255), nullable=True),
    sa.Column('pass_condition', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('scoring_weight', sa.Float(), nullable=False),
    sa.Column('copilot_blocking', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['assessment_parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_rules_id'), 'assessment_rules', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_rules_parameter_id'), 'assessment_rules', ['parameter_id'], unique=False)
    op.create_table('assessments',
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('collaboration_score', sa.Float(), nullable=True),
    sa.Column('licensing_score', sa.Float(), nullable=True),
    sa.Column('copilot_eligible_user_count', sa.Integer(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('critical_findings', sa.Integer(), nullable=True),
    sa.Column('high_findings', sa.Integer(), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_tenant_id'), 'assessments', ['tenant_id'], unique=False)
    op.create_index('ix_assessments_tenant_status_created_at', 'assessments', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_assessments_triggered_by_user_id'), 'assessments', ['triggered_by_user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_tenant_event_created_at', 'audit_logs', ['tenant_id', 'event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked_expires', 'refresh_tokens', ['user_id', 'revoked', 'expires_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jwt_jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_jwt_jti'), 'user_sessions', ['jwt_jti'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_user_revoked_expires', 'user_sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_table('assessment_findings',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('parameter_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.JSON(), nullable=True),
    sa.Column('evaluated_value', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('score_contribution', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['assessment_parameters.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['assessment_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_findings_assessment_id'), 'assessment_findings', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_findings_id'), 'assessment_findings', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_findings_parameter_id'), 'assessment_findings', ['parameter_id'], unique=False)
    op.create_index(op.f('ix_assessment_findings_rule_id'), 'assessment_findings', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_findings_rule_id'), table_name='assessment_findings')
    op.drop_index(op.f('ix_assessment_findings_parameter_id'), table_name='assessment_findings')
    op.drop_index(op.f('ix_assessment_findings_id'), table_name='assessment_findings')
    op.drop_index(op.f('ix_assessment_findings_assessment_id'), table_name='assessment_findings')
    op.drop_table('assessment_findings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_revoked_expires', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_jwt_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_revoked_expires', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_event_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessments_triggered_by_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_tenant_id'), table_name='assessments')
    op.drop_index('ix_assessments_tenant_status_created_at', table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_assessment_rules_parameter_id'), table_name='assessment_rules')
    op.drop_index(op.f('ix_assessment_rules_id'), table_name='assessment_rules')
    op.drop_table('assessment_rules')
    op.drop_index(op.f('ix_users_microsoft_tid'), table_name='users')
    op.drop_index(op.f('ix_users_microsoft_oid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_connected_tenants_tenant_id'), table_name='connected_tenants')
    op.drop_index(op.f('ix_connected_tenants_id'), table_name='connected_tenants')
    op.drop_table('connected_tenants')
    op.drop_index(op.f('ix_assessment_parameters_parameter_key'), table_name='assessment_parameters')
    op.drop_index(op.f('ix_assessment_parameters_id'), table_name='assessment_parameters')
    op.drop_index(op.f('ix_assessment_parameters_category'), table_name='assessment_parameters')
    op.drop_table('assessment_parameters')
    # ### end Alembic commands ###
